#! /Users/alex/.rvm/bin/python

import goslate
from sys import exit

gs = goslate.Goslate()
text = raw_input(' -> ')
while( text != 'exit' ):
    try:
        print( ' --> ' + gs.translate(text, 'it') )
    except:
        print('Error translating\n')
        exit(1)
    text = raw_input(' -> ')
print('Terminated\n')
